### PR TITLE
Prop no heat stroke in water

### PR DESCRIPTION
**Pull request by CHeuberger**
The player should not get hit by Heat Stroke while IN Water (Fresh and Salt {and Hot?}).
Just a proposal, not sure if and how that could impact the game balance... 
but I think it is a bit more believable [:-)

'So we can swim longer near the equator'

### CODE REVIEW

**Comment by CHeuberger** [comment]
note: this builds on #784  ...

**Comment by Kittychanley** [comment]
In reality, you're actually more likely to get a heat stroke while you are in the water because of the water reflecting the sun's rays. It's the same reason you'll get much more badly sunburned while swimming than just staying on the beach.

**Comment by CHeuberger** [comment]
wait sunburn is not the same as heat stroke - at least as I learned during lots of years of lifeguard training/activities!
As I learned there are two distinct problems:

1 - Heat stroke: excessive body temperature because of environmental heat exposure and lack of heat regulation. Main counteraction is cooling, eventually in (cold) water - obviously HOT water would not be that helpful.

2 - Sun stroke - not sure if that is the correct English term, in German it's Sonnenstich (sun sting). Caused by long exposure of head and neck area to direct sun light causing an irritation of the meninges - not related to temperature or dehydration. This sure would can also occur in water. Easiest counteraction: use a hat or stay in shadow! So, in TFC it would be enough to be wearing any helmet to avoid this...

**Comment by Kittychanley** [comment]
Not very many people know the difference between a heat stroke and a sun stroke, so it's easier to just consider them both the same thing in terms of gameplay.

**Pull request closed without merging**
