### PR TITLE
removed unwanted fall-through in switch;

### PR DESCRIPTION
**Pull request by CHeuberger**
possible NPE error in loading ore config;
tryed to make ore config loading a bit more understandable;
removed some needless uses of StringBuilder

### CODE REVIEW

**Comment by Kittychanley** [comment]
Is there a specific reason you changed the first string in the ore data to be lowercase? Did you test to make sure that doing that change isn't going to screw up existing worlds that were previously using the Title Case names?

**Comment by CHeuberger** [comment]
it was because each default ore category was being added 2 times to the ore list, once in Title Case and the second time in lowercase since config.getCategoryNames() returns the names in lowercase. I could not find the name being used anywhere else (just TFC), only here in the loop to check if the category already was on the list.

**Comment by CHeuberger** [comment]
if you feel better, I could leave the names in Title Case and change the checking to be case insensitive - maybe some other Mod is using this key...

**Comment by Kittychanley** [comment]
I have a hunch that this PR won't play nicely with #788. I'll go ahead and fix the switch fall-through, and then revisit both this and #788 for .23 after we have released .22

I would prefer to leave the names as-is, just as a an extra preventative measure to make sure it doesn't break anything.

**Comment by CHeuberger** [comment]
but the name was only a minor part of the PR, I also changed the logic to avoid having the standard categories added two times (once with the default values, second with the eventually used changed values)

**Comment by Kittychanley** [comment]
Did you go look at #788? It's a heavy rewrite of the same file.

**Comment by CHeuberger** [comment]
shit... sorry I haven't  seen that one (but Github also had problems with it: "Sorry, we could not display the entire diff because too many files (506) changed.") - I see the problem!

**Comment by dries007** [comment]
This is for sure incompattible with #788, though I can add this fix to that branch if the issue still exists there. (I have not checked)

**Comment by CHeuberger** [comment]
I am pretty sure that it still is there: getCategoryNames() return all names lower case, but the names added to the OreList are title case  and containsKey() is case sensitive.
Solutions:
- use lower case when adding to the OreList;
- set Configuration to be case sensitive (I think that is not so good at all);
- be case insensitive when checking if the key is already in OreList (best IMHO, consistent with Configuration)

**Comment by dries007** [comment]
I made a case insensitive hashmap (used for the OreList)
This fixes all issues besides the unwanted fall-through right?

**Comment by CHeuberger** [comment]
Yes, perfect (or a bit more than that [:-)

**Comment by CHeuberger** [comment]
I think this can be closed, hoping that #788 will be included...

**Pull request closed without merging**
