### PR TITLE
Somebody added pakratt13 instead limonite

### PR DESCRIPTION
**Pull request by Mexahoid**

### CODE REVIEW

**Comment by Kittychanley** [comment]
That's because that achievement is in honor of pakratt13

**Comment by Mexahoid** [comment]
Why is it in russian lang then?

**Comment by Kittychanley** [comment]
Because achievements have a message that pops up on the screen. That line is the russian translation for that message.

**Comment by Mexahoid** [comment]
I mean why russian, not original english lang? It doesn't seem that he is russian.

**Comment by Kittychanley** [comment]
Because he deserves credit for the achievement no matter what language the game is being played with?

**Comment by Mexahoid** [comment]
I have never heard about him in russian community. So I didn't think that he is famous or well-known.

**Comment by Kittychanley** [comment]
He is one of the primary people that made TFC popular. He is famous and well-known in regards to TerraFirmaCraft. He is an english youtuber and twitch.tv streamer, which is why you may have not heard of him, but that doesn't mean that he isn't still popular.

**Comment by Mexahoid** [comment]
I understand that he is popular. I'm just curious, why is reference to him in russian lang file for TFC. Some people do not use russian language in MC client because it looks awful. Maybe half of 1/3 of that lang users do not know who is pakratt13.

**Comment by Kittychanley** [comment]
All of the non-english lang files are edited by the community. That means that there was at least one person out there, who contributed to editing the lang files, that is a fan of pakratt. Russian is not the only language that references him for that achievement, although it may be the only one that does so directly with his name.

**Comment by Mexahoid** [comment]
Well, now I see your point. I was only curious about that strange replacing "LI-MO-NIITE" achievement.

**Comment by Kittychanley** [comment]
In the English lang file, the text for the achievement is a direct quote, phonetically spelled out of a catchphrase that pakratt uses. That catchphrase, when phonetically spelled out, doesn't always translate well into other languages. When that is the case, it's easier to just directly reference pakratt instead.

**Comment by Mexahoid** [comment]
Ok then. Understood.

**Pull request closed without merging**
