### PR TITLE
Update es_ES translation

### PR DESCRIPTION
**Pull request by tinproject**
Update the es_ES (spanish of Spain) translation. Mainly filling the empty texts and some minor corrections.
In the future surely needs some changes and adjustments to embody a common style, but for now it's better a not completely correct translation that none translation.

### CODE REVIEW

**Comment by Kittychanley** [comment]
Please direct all translation changes to @aliceingame using the following forum post: http://terrafirmacraft.com/f/topic/4124-tfc-translation/

**Comment by aliceingame** [comment]
It's not a problem to submit an update, the problem is that if the language file have not been made from the spreadsheet, then the next time that there is a change in the en_US, like new lines, then all the modifications will be lost when I re-create all the language files to match the spreadsheet.

As a side note, all the spanish translations are the same, it's just copies of the same file with a different name.

**Comment by tinproject** [comment]
@aliceingame is there a way that I can send you a .csv with the texts, or something, to made a batch update to the spreadsheet? It's my fault for don't read the forum, but I spend a whole day off and I'm not sure when I will have the time to update the spreadsheet manually.

The translation is for Castillian Spanish, maybe it's interesting to create a new language column for Latin American Spanish, or rename the existing one and add a new foe es_ES.
Lots of words in Spanish have different meanings in Spain than in Latin American, specially with old vocabulary terms that a game like TFC need.

**Comment by aliceingame** [comment]
Yes it is possible to make new columns for the latin american spanish. We already have regional differences for the french and portuguese translations in the spreadsheet.
It was not done bedore as the Spanish translation had not been fully translated for some time.

I found the es translation on your branch. I'ts easy to mass update when you use a simple text editor like Notepad++, only hate to replace all #= to nothing (to delete, as you do not want to have any = before words that are not part of the translation) then replace all = to tabs. Then copy paste in a spreadsheet software, as the tabs will make it into two rows so you can copy the translater row to the translation spreadsheet.

**Comment by aliceingame** [comment]
I also had to change == to =, but it's done

Translation is at 99.7%, so there is 21 lines missing. It's easier to spot on the spreadsheet as they are in red.

also created a new row for latin american spanish

**Comment by tinproject** [comment]
@aliceingame I've notice that you fill the most part of the spreadsheet, I've just finished filling the spreadsheet, some typos and some unfilled text (achievements mainly).
When you have time please commit the file so I can build the game and catch translation mistakes when I play. Thanks.

**Comment by aliceingame** [comment]
@tinproject you can always use the export tab to create the file. You only have to select the language you want and copy/paste the second row in the language file. And you can also use the official release to test, you only have to open the .jar file (with 7zip for example) and manually change the .lang file in it. 

I saw that there is some changes in the en_US, so I will update the spreadsheet first.

**Pull request closed without merging**
